
dark_addon.interface = { }

dark_addon.interface.loading_messages = {
  "Reticulating splines...",
  "Swapping time and space...",
  "Tokenizing real life...",
  "Bending the spoon...",
  "We need a new fuse...",
  "The bits are breeding",
  "Follow the white rabbit",
  "Are we there yet?",
  "It's not you. It's me.",
  "Counting backwards from Infinity",
  "Embiggening Prototypes",
  "Creating time-loop inversion field",
  "Spinning the wheel of fortune...",
  "I'm sorry Dave, I can't do that.",
  "Adjusting flux capacitor...",
  "Cleaning off the cobwebs...",
  "Spinning the hamster…",
  "Stay awhile and listen..",
  "Convincing AI not to turn evil..",
  "How did you get here?",
  "Constructing additional pylons...",
  "Roping some seaturtles...",
  "Dividing by zero...",
  "Proving P=NP...",
  "Entangling superstrings...",
  "Twiddling thumbs...",
  "Trying to sort in O(n)...",
  "Winter is coming...",
  "Aw, snap! Not..",
  "Ordering 1s and 0s...",
  "Updating dependencies...",
  "Please wait... Consulting the manual...",
  "Mining some bitcoins...",
  "Initializing the initializer...",
  "Optimizing the optimizer...",
  "Pushing pixels...",
  "Building a wall...",
  "Running with scissors...",
  "Definitely not a virus...",
  "You may call me Steve.",
  "Obfuscating quantum entaglement",
  "Making breakfast...",
  "Combing the desert...",
  "Yes, yes. Yes. Without the oops."
}
